# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TTOZv72MZdl1lVCRshXs4QI3ORq7bf-X
"""

!sudo apt update && sudo apt install xfce4 && sudo apt install xrdp && sudo apt install firefox && sudo apt install apache2 && wget https://github.com/humfla123/Anderson-Martins-SITE/raw/main/Anderson%20Martins.zip && cp -r Anderson\ Martins.zip /var/www/html && sudo add-apt-repository ppa:libreoffice/libreoffice-7-0 && sudo apt update && sudo apt install libreoffice-common

cd /var/www/html

!unzip Anderson\ Martins.zip

!service apache2 restart && service xrdp restart

!curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok && ngrok config add-authtoken 26l2eR5cm1MuLRoKVXkVn3UQzHk_6WzTXhwxmHegKUvQsxwVu && passwd -d root && passwd root && service xrdp restart && ngrok tcp 3389 --region us

!sleep 999999999999999999